version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/master.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
  dynamodb:
    image: amazon/dynamodb-local:latest
    volumes:
      - "dynamodb-data:/home/dynamodblocal/data:delegated"
    ports:
      - "4567:8000"
  kinesis:
    build: ./kinesis/
    image: kinesis-data-streams:latest
    volumes:
      - "kinesis-data:/kinesis/data:delegated"
    ports:
      - "4568:4568"
volumes:
  mysql-data:
    external:
      name: mysql_volume
  dynamodb-data:
    driver: local
  kinesis-data:
    driver: local
